[build]
  base = 'frontend'
  publish = 'frontend/build'
  command = 'npm install && npm run build'

[build.environment]
  NODE_VERSION = "v12.14.0"

[context.production]
  command = "echo 'production'; npm install && npm run build"

[context.production.environment]
  NODE_ENV = "production"

[context.develop]
  command = "echo 'development'; npm install && npm run build"

[context.develop.environment]
  NODE_ENV = "development"

[context.netlify-deploy]
  command = "echo 'netlify-deploy'; npm install && npm run build"

[context.netlify-deploy.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
